# gating options

# log levels
log_info: true
log_warnings: true
log_errors: true
log_debug: true

# meta info
log_file: true
start_time: false
os_version: true
python_version: true
whoami: true
file_name: true
file_dir: true
pid: true
git_info: true
