from practice import hello_world
from practice import print_file_name_of_calling_script
from practice import print_directory_of_calling_script

hello_world()
print_file_name_of_calling_script()
print_directory_of_calling_script()
